### ISSUE TITLE
Hi,bower install editable-grid redirect to https://github.com/Roobyx/editableGrid.git

### ISSUE THREAD

**Issue by magixsource** [skinnybrit51/editable-grid#100]
I try to install editable-grid by bower, but this request redirect to that repo. this repo name is multi-use.

**Comment by skinnybrit51** [comment]
First come first served on these package sites. You can download the js & css from here http://skinnybrit51.com/editable-grid/

**Comment by magixsource** [comment]
Okay,Thanks.
