### ISSUE TITLE
Compatibility with Electron

### ISSUE THREAD

**Issue by dsl101** [skinnybrit51/editable-grid#98]
I'm _very_ new to electron, so might just have something badly set up, but I can't get the basic 'hello world' of editable-grid to display properly. So far I've:

- Set up and got _electron_ hello world working OK
- Installed editable-grid via npm
- Made sure jQuery is working within electron (so I could use `el: $('body')`)

From what I can see, the app's content is correct, `grid.css` (not using LESS) is being included, and the empty `<body>` tag ends up with the correct table contents. But the display just doesn't look right - see screenshot.

Have I missed something obvious? Or is there something about editable-grid that means it wouldn't work with electron? I'm sure there's other info you might need - please let me know...

electron app source:

awsmanager.html:

	<html style="background: #fff">
		<head>
			<link rel="stylesheet" href="./grid.css">
			<script>window.$ = window.jQuery = require('jquery');</script>
			<script src='./awsmanager.js'></script>
		</head>
		<body>
		</body>
	</html>

awsmanager.js:

	var Grid = require('editable-grid');

	$(function() {
		console.log('Loaded');
		var grid = new Grid({
			el: $('body'),
			columns: [
				{
					id: 'a',
					title: 'a',
					width: '33.3%'
				},
				{
					id: 'b',
					title: 'b',
					width: '33.3%',
					alignment: 'right',
					titleAlignment: 'center'
				},
				{
					id: 'c',
					title: 'c',
					width: '33.3%',
					alignment: 'center',
					titleAlignment: 'right'
				}
			],
			data: [
				{
					id: 'id-1',
					a: 'a',
					b: 'b',
					c: 'c'
				},
				{
					id: 'id-2',
					a: 'a',
					b: 'b',
					c: 'c'
				}
			]
		});

		grid.render();
	});

resulting app:

![image 2](https://cloud.githubusercontent.com/assets/900542/14208268/7e899350-f816-11e5-99a9-522bb6b12905.png)

**Comment by skinnybrit51** [comment]
Just missing bootstrap css. Needs to be before grid.css link
`
<link rel="stylesheet" href="./grid.css">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"/>
`

**Comment by dsl101** [comment]
Ah, OK. I was looking at [this](https://www.npmjs.com/package/editable-grid) page and it didn't list bootstrap as a dependency - presumably it's only possible to put npm _packages_ in that section...

Anyway, many thanks.
